###
# Create an airplane
POST http://localhost:3000/api/v1/airplanes
Content-Type: application/json

{
    "modelNumber": "space342",
    "capacity": 180
}

###
# Get all airplanes
GET http://localhost:3000/api/v1/airplanes

###
# Get Airplane by ID
GET http://localhost:3000/api/v1/airplanes/1