###
# Create an airplane
POST http://localhost:3000/api/v1/airplanes
Content-Type: application/json

{
    "modelNumber": "space342",
    "capacity": 180
}

###
# Get all airplanes
GET http://localhost:3000/api/v1/airplanes

###
# Get Airplane by ID
GET http://localhost:3000/api/v1/airplanes/10

###
# Delete Airplane by ID
DELETE http://localhost:3000/api/v1/airplanes/10

###
# Update Airplane by ID
PATCH http://localhost:3000/api/v1/airplanes/11
Content-Type: application/json

{
    "capacity": 450
}


###
# Create city
POST http://localhost:3000/api/v1/cities
Content-Type: application/json

{
    "name": "Hyderabad"
}

###

DELETE http://localhost:3000/api/v1/cities/1

###
PATCH http://localhost:3000/api/v1/cities/2
Content-Type: application/json

{
    "name": "New York"
}

###
# Create Airport

POST http://localhost:3000/api/v1/airports
Content-Type: application/json

{
    "name": "Mallu airport",
    "code": "HYD",
    "cityId": 12
}

###
# Get Airports
GET http://localhost:3000/api/v1/airports


###
# Get Airport
GET http://localhost:3000/api/v1/airports/4 HTTP/1.1

###
# Delete Airport
DELETE http://localhost:3000/api/v1/airports/4

###
# Update Airport
PATCH http://localhost:3000/api/v1/airports/1
Content-Type: application/json

{
    "name": "CSI Airport"
}