###
# Create an airplane
POST http://localhost:3000/api/v1/airplanes
Content-Type: application/json

{
    "modelNumber": "space342",
    "capacity": 180
}

###
# Get all airplanes
GET http://localhost:3000/api/v1/airplanes

###
# Get Airplane by ID
GET http://localhost:3000/api/v1/airplanes/10

###
# Delete Airplane by ID
DELETE http://localhost:3000/api/v1/airplanes/10

###
# Update Airplane by ID
PATCH http://localhost:3000/api/v1/airplanes/11
Content-Type: application/json

{
    "capacity": 450
}


###
# Create city
POST http://localhost:3000/api/v1/cities
Content-Type: application/json

{
    "name": "New Delhi"
}

###

DELETE http://localhost:3000/api/v1/cities/1